// Generated by CoffeeScript 1.6.3
(function() {
  var changeInterval, interval, socket, start;

  socket = io.connect('http://naked.party.sh/consumer');

  interval = void 0;

  changeInterval = function(newBpm) {
    if (interval) {
      clearInterval(interval);
    }
    return interval = setInterval(function() {
      return $("body").trigger("beatFireBeat");
    }, 60000 / newBpm);
  };

  start = function() {
    return socket.on('bpm', changeInterval);
  };

  start();

}).call(this);
