// Generated by CoffeeScript 1.6.3
(function() {
  var changeInterval, interval, socket;

  socket = io.connect('http://party.naked.sh:80/consumer');

  console.log("BEATFIRE");

  interval = void 0;

  changeInterval = function(newBpm) {
    console.log("new bpm detected", newBpm);
    if (interval) {
      clearInterval(interval);
    }
    return interval = setInterval(function() {
      return $("body").trigger("beatFireBeat");
    }, 60000 / newBpm);
  };

  socket.on('bpm', changeInterval);

}).call(this);
